---
title: Stolpersteine Heilbronn
timezone: UTC
collections:
  actions:
    title: Aktionen
    output: true
    permalink: "/aktionen/:name:output_ext"
  list:
    title: Liste
    output: true
    permalink: "/list/:name:output_ext"
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: actions
  values:
    layout: action
- scope:
    path: ''
    type: item
  values:
    layout: item
    title: 
    paten: "Name Nachname"
    steine:
    - - HIER WOHNTE
      - VORNAME NACHNAME
      - ''
      - ''
      - '1900'
      - DEPORTIERT JAHR
      - ERMORDET IN
      - ORT
      - ''
email: lukas@himsel.me
description: ''
baseurl: "/stolpersteine"
url: https://opendata-heilbronn.github.io
markdown: kramdown
permalink: pretty
exclude:
- scripts/
lat: 49.1426929
long: 9.210878999999977
blog: false
